server:
  port: 8003 # Random Port : 0

spring:
  profiles:
    default: dev
  application:
    name: analysis-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  r2dbc:
    url: r2dbc:mysql://localhost:3306/r2test?serverTimezone=KST&characterEncoding=UTF-8
    username: root
    password: 1234

cryptutil:
  key: "1234567890123456"

eureka:
  instance:
    hostname: localhost
    instance-id : ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

  client:
    registerWithEureka: true #gateway는 eureka에 등록할필요 없다. gateway는
    fetchRegistry: true #gateway는 eureka가 찾을 필요 없다
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/ # 서버가 가진 위치값


---

spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: r2dbc:mysql://clonecoin-analysis-db.crtppt0lvgk7.ap-northeast-2.rds.amazonaws.com:3306/analysis?serverTimezone=KST&characterEncoding=UTF-8
    username: root
    password: 1234

---

spring:
  config:
    activate:
      on-profile: dev
